<a href="https://colab.research.google.com/github/Syntax-code/Codes/blob/master/tic_tac_toe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Full code 

In [110]:
import numpy as np

def check_zero(board):
    return any(1 in sub for sub in board)
    
def won(board):
    sum1= 0
    sum2= 0
    sum3= 0
    sum4= 0
    sum5= 0
    sum6= 0
    sum7= 0
    sum8= 0
    for i in range(3):
        sum1 +=board.item((0,i))
    for i in range(3):
        sum2 +=board.item((i,0))
    for i in range(3):
        sum3 +=board.item((i,i))
    for i in range(3):
        sum4 +=board.item((i,1))
    for i in range(3):
        sum5 +=board.item((i,2-i))
    for i in range(3):
        sum6 +=board.item((i,2))
    for i in range(3):
        sum7 +=board.item((1,i))
    for i in range(3):
        sum8 +=board.item((2,i))
    if (sum1==0 or sum2==0 or sum3==0 or sum4==0 or sum5==0 or sum6==0 or sum7==0 or sum8==0) :
        return 1
        
    elif(sum1==6 or sum2==6 or sum3==6 or sum4==6 or sum5==6 or sum6==6 or sum7==6 or sum8==6):
        return 2
        
    elif check_zero(board) == True :
        return -1
        
    else:
        return 0
    


def is_solved(board):
    board = np.array(board)
    board[board == 0] = 4
    board[board == 1] = 0
    board[board == 4] = 1
    return won(board)

board = [[0, 0, 1],
         [0, 1, 2],
         [2, 1, 0]]
print(is_solved(board))

-1


In [0]:
break down code

In [0]:
import numpy as np

In [0]:
board = [[0, 0, 1],
         [0, 1, 2],
         [2, 1, 0]]

In [0]:
board = np.array(board)

In [97]:
board[board == 0] = 4
board[board == 1] = 0
board[board == 4] = 1
print(board)

[[1 1 0]
 [1 0 2]
 [2 0 1]]


In [98]:
print(np.choose([0,1,2], board))

[1 0 1]


1st

In [99]:
sum1= 0
for i in range(3):
  sum1 +=board.item((0,i))
print(sum1)

2


2nd

In [100]:
sum2= 0
for i in range(3):
  sum2 +=board.item((i,0))
print(sum2)

4


3rd

In [101]:
sum3= 0
for i in range(3):
  sum3 +=board.item((i,i))
print(sum3)

2


4th

In [102]:
sum4= 0
for i in range(3):
  sum4 +=board.item((i,1))
print(sum4)

1


5th

In [103]:
sum5= 0
for i in range(3):
  sum5 +=board.item((i,2-i))
print(sum5)

2


6th

In [104]:
sum6= 0
for i in range(3):
  sum6 +=board.item((i,2))
print(sum6)

3


7th

In [105]:
sum7= 0
for i in range(3):
  sum7 +=board.item((1,i))
print(sum7)

3


8th

In [106]:
sum8= 0
for i in range(3):
  sum8 +=board.item((2,i))
print(sum8)

3


check if sums have ans 3 or 6

In [108]:
if (sum1==0 or sum2==0 or sum3==0 or sum4==0 or sum5==0 or sum6==0 or sum7==0 or sum8==0) :
  print('X won')
elif(sum1==6 or sum2==6 or sum3==6 or sum4==6 or sum5==6 or sum6==6 or sum7==6 or sum8==6):
  print('O won')
elif (sum1<3 or sum2<3 or sum3<3 or sum4<3 or sum5<3 or sum6<3 or sum7<3 or sum8<3) :
  print('game still left')
else:
  print('draw')

game still left


In [109]:
any(1 in sub for sub in board)

True